# syntax=docker/dockerfile:1

FROM nvidia/cuda:12.2.0-base-ubuntu20.04
RUN apt-get update && apt-get install -y -q python3 python3-pip
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
# https://github.com/marella/ctransformers#cuda
RUN pip3 install ctransformers[cuda]
COPY . .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
