# syntax=docker/dockerfile:1

FROM nvidia/cuda:12.2.0-devel-ubuntu22.04
RUN apt-get update \
    && apt-get install -y --no-install-recommends g++ python3-dev python3-pip \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get purge -y --auto-remove g++ python3-dev python3-pip
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
# https://github.com/marella/ctransformers#gptq
RUN pip3 install ctransformers[gptq]
COPY . .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
