replicas: 1

deployment:
  image: quay.io/chenhunghan/ialacol:latest
  # env:
    # DEFAULT_MODEL_HG_REPO_ID: TheBloke/Llama-2-7B-Chat-GGML
    # DEFAULT_MODEL_FILE: llama-2-7b-chat.ggmlv3.q4_0.bin
    # LOGGING_LEVEL: DEBUG
    # MODELS_FOLDER: models
    # CACHE_FOLDER: cache
    # THREADS: 8
    # BATCH_SIZE: 8
    # CONTEXT_LENGTH: 1024
resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

cache:
  persistence:
    size: 10Gi
    accessModes:
      - ReadWriteOnce
    # Optional. e.g. "gp2-unencrypted"
    storageClass: ~
# the path to mount the cache volume on the container
cacheMountPath: /app/cache

model:
  persistence:
    size: 24Gi
    accessModes:
      - ReadWriteOnce
    # Optional. e.g. "gp2-unencrypted"
    storageClass: ~
# the path to mount the model volume on the container
modelMountPath: /app/models

service:
  type: ClusterIP
  port: 8000
  annotations: {}
  # If using an AWS load balancer, you'll need to override the default 60s load balancer idle timeout
  # service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "1200"
nodeSelector: {}
tolerations: []
  # e.g.
  # - key: "ai"
  #   operator: "Exists"
  #   effect: "NoSchedule"
affinity: {}
  # e.g.
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: nodegroup-ai
  #         operator: In
  #         values:
  #         - "true"
