apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Chart.Name }}
      app.kubernetes.io/name: {{ .Chart.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app.kubernetes.io/instance: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.deployment.image }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: GF_REPO
            value: {{ .Values.deployment.env.GF_REPO | quote }}
          - name: MODEL_FILE
            value: {{ .Values.deployment.env.MODEL_FILE | quote }}
          volumeMounts:
          - mountPath: {{ .Values.cacheMountPath }}
            name: cache
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}
      tolerations:
{{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
      nodeSelector:
{{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      affinity:
{{- if .Values.affinity }}
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
