apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Chart.Name }}
      app.kubernetes.io/name: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app.kubernetes.io/instance: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.deployment.image }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- if .Values.deployment.env?.DEFAULT_MODEL_HG_REPO_ID }}
          - name: DEFAULT_MODEL_HG_REPO_ID
            value: {{ .Values.deployment.env.DEFAULT_MODEL_HG_REPO_ID | quote }}
          {{- end }}
          {{- if .Values.deployment.env?.DEFAULT_MODEL_FILE }}
          - name: DEFAULT_MODEL_FILE
            value: {{ .Values.deployment.env.DEFAULT_MODEL_FILE | quote }}
          {{- end }}
          {{- if .Values.deployment.env?.LOGGING_LEVEL }}
          - name: LOGGING_LEVEL
            value: {{ .Values.deployment.env.LOGGING_LEVEL | quote }}
          {{- end }}
          {{- if .Values.deployment.env?.MODELS_FOLDER }}
          - name: MODELS_FOLDER
            value: {{ .Values.deployment.env.MODELS_FOLDER | quote }}
          {{- end }}
          {{- if .Values.deployment.env?.CACHE_FOLDER }}
          - name: CACHE_FOLDER
            value: {{ .Values.deployment.env.CACHE_FOLDER | quote }}
          {{- end }}
          {{- if .Values.deployment.env?.THREADS }}
          - name: THREADS
            value: {{ .Values.deployment.env.THREADS | quote }}
          {{- end }}
          {{- if .Values.deployment.env?.BATCH_SIZE }}
          - name: BATCH_SIZE
            value: {{ .Values.deployment.env.BATCH_SIZE | quote }}
          {{- end }}
          {{- if .Values.deployment.env?.CONTEXT_LENGTH }}
          - name: CONTEXT_LENGTH
            value: {{ .Values.deployment.env.CONTEXT_LENGTH | quote }}
          {{- end }}
          volumeMounts:
          - mountPath: {{ .Values.cacheMountPath }}
            name: cache
          - mountPath: {{ .Values.modelMountPath }}
            name: model
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-cache
      - name: model
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-model
      tolerations:
{{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
      nodeSelector:
{{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      affinity:
{{- if .Values.affinity }}
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
