apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Chart.Name }}
      app.kubernetes.io/name: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app.kubernetes.io/instance: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.deployment.image }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: DEFAULT_MODEL_HG_REPO_ID
            value: {{ (.Values.deployment.env).DEFAULT_MODEL_HG_REPO_ID | quote }}
          - name: DEFAULT_MODEL_FILE
            value: {{ (.Values.deployment.env).DEFAULT_MODEL_FILE | quote }}
          - name: MODE_TYPE
            value: {{ (.Values.deployment.env).MODE_TYPE | quote }}
          - name: LOGGING_LEVEL
            value: {{ (.Values.deployment.env).LOGGING_LEVEL | quote }}
          - name: TOP_K
            value: {{ (.Values.deployment.env).TOP_K | quote }}
          - name: TOP_P
            value: {{ (.Values.deployment.env).TOP_P | quote }}
          - name: TEMPERATURE
            value: {{ (.Values.deployment.env).TEMPERATURE | quote }}
          - name: REPETITION_PENALTY
            value: {{ (.Values.deployment.env).REPETITION_PENALTY | quote }}
          - name: LAST_N_TOKENS
            value: {{ (.Values.deployment.env).LAST_N_TOKENS | quote }}
          - name: SEED
            value: {{ (.Values.deployment.env).SEED | quote }}
          - name: BATCH_SIZE
            value: {{ (.Values.deployment.env).BATCH_SIZE | quote }}
          - name: THREADS
            value: {{ (.Values.deployment.env).THREADS | quote }}
          - name: MAX_TOKENS
            value: {{ (.Values.deployment.env).MAX_TOKENS | quote }}
          - name: STOP
            value: {{ (.Values.deployment.env).STOP | quote }}
          - name: CONTEXT_LENGTH
            value: {{ (.Values.deployment.env).CONTEXT_LENGTH | quote }}
          - name: GPU_LAYERS
            value: {{ (.Values.deployment.env).GPU_LAYERS | quote }}
          - name: TRUNCATE_PROMPT_LENGTH
            value: {{ (.Values.deployment.env).TRUNCATE_PROMPT_LENGTH | quote }}
          volumeMounts:
          - mountPath: /app/models
            name: model
      volumes:
      - name: model
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-model
      tolerations:
{{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
      nodeSelector:
{{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      affinity:
{{- if .Values.affinity }}
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
