apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.service.annotations }}
  annotations: {{ .Values.service.annotations }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
  type: "{{ .Values.service.type }}"
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
      name: http
