apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
  type: "{{ .Values.service.type }}"
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
      name: http
